<a href="https://colab.research.google.com/github/archanaseru/datascience/blob/main/pandas_practice_2nd_may.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
import pandas as pd

In [ ]:
# in pandas, data objects are called dataframes.
# dataframe --> collection of rows and columns --> maintains data in tabular format (similar to sql tables)

In [ ]:
# each list should be  column in a dataframe.
id = [101, 102, 103, 104, 105, 106]
name = ['amar', 'amala', 'siva', 'sivani', 'mani', 'manisha']
age = [25, 26, 30, 23, 24, 35]
salary = [10000, 30000, 60000, 90000, 100000, 90000]
gender = ['m', 'f', 'm', 'f', 'm', 'f']
dno = [11, 12, 13, 11, 12, 14]

In [ ]:
df = pd.DataFrame([id, name,age,  salary, gender, dno])
print(df)

       0      1      2       3       4        5
0    101    102    103     104     105      106
1   amar  amala   siva  sivani    mani  manisha
2     25     26     30      23      24       35
3  10000  30000  60000   90000  100000    90000
4      m      f      m       f       m        f
5     11     12     13      11      12       14

In [ ]:
dinfo = {
        "id": id,
         "name" : name,
         "age" : age,
         "salary" : salary,
         "gender" : gender,
         "dno" : dno
         }

In [ ]:
df = pd.DataFrame(dinfo)
print(df) # prints few rows of a data frame

    id     name  age  salary gender  dno
0  101     amar   25   10000      m   11
1  102    amala   26   30000      f   12
2  103     siva   30   60000      m   13
3  104   sivani   23   90000      f   11
4  105     mani   24  100000      m   12
5  106  manisha   35   90000      f   14

In [ ]:
print(df.to_string()) # to print all rows of a dataframe

    id     name  age  salary gender  dno
0  101     amar   25   10000      m   11
1  102    amala   26   30000      f   12
2  103     siva   30   60000      m   13
3  104   sivani   23   90000      f   11
4  105     mani   24  100000      m   12
5  106  manisha   35   90000      f   14

In [ ]:
df.head() # first 5 rows.

    id    name  age  salary gender  dno
0  101    amar   25   10000      m   11
1  102   amala   26   30000      f   12
2  103    siva   30   60000      m   13
3  104  sivani   23   90000      f   11
4  105    mani   24  100000      m   12

In [ ]:
df.tail()

    id     name  age  salary gender  dno
1  102    amala   26   30000      f   12
2  103     siva   30   60000      m   13
3  104   sivani   23   90000      f   11
4  105     mani   24  100000      m   12
5  106  manisha   35   90000      f   14

In [ ]:
df.head(3)

    id   name  age  salary gender  dno
0  101   amar   25   10000      m   11
1  102  amala   26   30000      f   12
2  103   siva   30   60000      m   13

In [ ]:
df.tail(3)

    id     name  age  salary gender  dno
3  104   sivani   23   90000      f   11
4  105     mani   24  100000      m   12
5  106  manisha   35   90000      f   14

In [ ]:
info = [(101,'siva', 10000), (102,'hari', 30000), (103, 'venu', 60000), (104, 'vani', 90000)]
dframe =  pd.DataFrame(info, columns= [['id', 'name', 'salary']])
print(dframe)

    id  name salary
0  101  siva  10000
1  102  hari  30000
2  103  venu  60000
3  104  vani  90000

In [ ]:
# to convert local objects into dataframe , two ways.
# way1
# df = pd.DataFrame(<dict>)
# key --> "Column name"
# value --> "List object"
# way2
# df = pd.DataFrame(list[tuples], columns = ['col1','col2',..'coln' ])

In [ ]:
df

    id     name  age  salary gender  dno
0  101     amar   25   10000      m   11
1  102    amala   26   30000      f   12
2  103     siva   30   60000      m   13
3  104   sivani   23   90000      f   11
4  105     mani   24  100000      m   12
5  106  manisha   35   90000      f   14

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      6 non-null      int64
 1   name    6 non-null      object
 2   age     6 non-null      int64
 3   salary  6 non-null      int64
 4   gender  6 non-null      object
 5   dno     6 non-null      int64
dtypes: int64(4), object(2)
memory usage: 416.0+ bytes

In [ ]:
# tranformations  on a dataframe.
df

    id     name  age  salary gender  dno
0  101     amar   25   10000      m   11
1  102    amala   26   30000      f   12
2  103     siva   30   60000      m   13
3  104   sivani   23   90000      f   11
4  105     mani   24  100000      m   12
5  106  manisha   35   90000      f   14

In [ ]:
df['tax'] = df['salary'] * 0.1
df

    id     name  age  salary gender  dno      tax
0  101     amar   25   10000      m   11   1000.0
1  102    amala   26   30000      f   12   3000.0
2  103     siva   30   60000      m   13   6000.0
3  104   sivani   23   90000      f   11   9000.0
4  105     mani   24  100000      m   12  10000.0
5  106  manisha   35   90000      f   14   9000.0

In [ ]:
df['hra'] = df['salary'] * 0.2
df

    id     name  age  salary gender  dno      tax      hra
0  101     amar   25   10000      m   11   1000.0   2000.0
1  102    amala   26   30000      f   12   3000.0   6000.0
2  103     siva   30   60000      m   13   6000.0  12000.0
3  104   sivani   23   90000      f   11   9000.0  18000.0
4  105     mani   24  100000      m   12  10000.0  20000.0
5  106  manisha   35   90000      f   14   9000.0  18000.0

In [ ]:
df['netsal'] = df['salary'] - df['tax'] + df['hra']
df

    id     name  age  salary gender  dno      tax      hra    netsal
0  101     amar   25   10000      m   11   1000.0   2000.0   11000.0
1  102    amala   26   30000      f   12   3000.0   6000.0   33000.0
2  103     siva   30   60000      m   13   6000.0  12000.0   66000.0
3  104   sivani   23   90000      f   11   9000.0  18000.0   99000.0
4  105     mani   24  100000      m   12  10000.0  20000.0  110000.0
5  106  manisha   35   90000      f   14   9000.0  18000.0   99000.0

In [ ]:
# Conditional transformations.
# convert gender short labels into  full lables.
# m --> "Male"
# f --> "Female"

def toGender(g):
   if g.lower()=='m':
      g='Male'
   elif g.lower()=='f':
     g = 'Female'
   else:
     g='Invalid'
   return g


df['gender'] = df['gender'].apply(toGender)
df

    id     name  age  salary  gender  dno      tax      hra    netsal
0  101     amar   25   10000    Male   11   1000.0   2000.0   11000.0
1  102    amala   26   30000  Female   12   3000.0   6000.0   33000.0
2  103     siva   30   60000    Male   13   6000.0  12000.0   66000.0
3  104   sivani   23   90000  Female   11   9000.0  18000.0   99000.0
4  105     mani   24  100000    Male   12  10000.0  20000.0  110000.0
5  106  manisha   35   90000  Female   14   9000.0  18000.0   99000.0

In [ ]:
def  toDept(d):
  dname = 'Other'
  dept = {11:"Marketing", 12:"Hr", 13:"Finance"}
  if d in dept:
    dname = dept[d]
  return dname

df['dname']  = df['dno'].apply(toDept)
print(df)

    id     name  age  salary  gender  dno      tax      hra    netsal  \
0  101     amar   25   10000    Male   11   1000.0   2000.0   11000.0
1  102    amala   26   30000  Female   12   3000.0   6000.0   33000.0
2  103     siva   30   60000    Male   13   6000.0  12000.0   66000.0
3  104   sivani   23   90000  Female   11   9000.0  18000.0   99000.0
4  105     mani   24  100000    Male   12  10000.0  20000.0  110000.0
5  106  manisha   35   90000  Female   14   9000.0  18000.0   99000.0

       dname
0  Marketing
1         Hr
2    Finance
3  Marketing
4         Hr
5      Other

In [ ]:
# salary --> grade
def toGrade(s):
   grade = 'D'
   if s>=100000:
     grade = 'A'
   elif s>=75000:
     grade='B'
   elif s>=50000:
     grade='C'
   return grade

df['grade'] = df['salary'].apply(toGrade)
print(df)

    id     name  age  salary  gender  dno      tax      hra    netsal  \
0  101     amar   25   10000    Male   11   1000.0   2000.0   11000.0
1  102    amala   26   30000  Female   12   3000.0   6000.0   33000.0
2  103     siva   30   60000    Male   13   6000.0  12000.0   66000.0
3  104   sivani   23   90000  Female   11   9000.0  18000.0   99000.0
4  105     mani   24  100000    Male   12  10000.0  20000.0  110000.0
5  106  manisha   35   90000  Female   14   9000.0  18000.0   99000.0

       dname grade
0  Marketing     D
1         Hr     D
2    Finance     C
3  Marketing     B
4         Hr     A
5      Other     B

In [ ]:
# age --> into age groups
def ageGroup(age):
   grp = 'old'
   if age<=12:
     grp = 'Child'
   elif age<=19:
     grp = 'teen'
   elif age<=35:
     grp = 'youth'
   elif age<=50:
     grp = 'adult'
   elif age<=65:
    grp = 'middle'
   return grp

df['ageGrp'] = df['age'].apply(ageGroup)
print(df)

    id     name  age  salary  gender  dno      tax      hra    netsal  \
0  101     amar   25   10000    Male   11   1000.0   2000.0   11000.0
1  102    amala   26   30000  Female   12   3000.0   6000.0   33000.0
2  103     siva   30   60000    Male   13   6000.0  12000.0   66000.0
3  104   sivani   23   90000  Female   11   9000.0  18000.0   99000.0
4  105     mani   24  100000    Male   12  10000.0  20000.0  110000.0
5  106  manisha   35   90000  Female   14   9000.0  18000.0   99000.0

       dname grade ageGrp
0  Marketing     D  youth
1         Hr     D  youth
2    Finance     C  youth
3  Marketing     B  youth
4         Hr     A  youth
5      Other     B  youth

In [ ]:
'''
two ways, to create or update columns --> to apply transformations.
df['new'] = 'any expression'
df['new_column'] = df['old_column'].apply(function)
'''

"\ntwo ways, to create or update columns --> to apply transformations. \ndf['new'] = 'any expression'\ndf['new_column'] = df['old_column'].apply(function)\n"

In [ ]:
# filters on data frame.

big_salaried = df[(df.salary >= 70000)]
print(big_salaried)

    id     name  age  salary  gender  dno      tax      hra    netsal  \
3  104   sivani   23   90000  Female   11   9000.0  18000.0   99000.0
4  105     mani   24  100000    Male   12  10000.0  20000.0  110000.0
5  106  manisha   35   90000  Female   14   9000.0  18000.0   99000.0

       dname grade ageGrp
3  Marketing     B  youth
4         Hr     A  youth
5      Other     B  youth

In [ ]:
df.query('salary >= 70000 and gender =="Male" ')

,id,name,age,salary,gender,dno,tax,hra,netsal,dname,grade,ageGrp
4,105,mani,24,100000,Male,12,10000.0,20000.0,110000.0,Hr,A,youth